### ISSUE TITLE
Docstrings cannot be generated in header files

### ISSUE THREAD

**Issue by Phil7789** [n0lavar/DoxygenComments#4]
When trying to create a comment in a .h file nothing happens, only the file docstring can be generated.

This would be useful for templates where you define and declare them inside the header file and no .cpp file exists for them.

**Comment by n0lavar** [comment]
Please add minimum reproducible example. AFAIK all should work fine even if function realisation is in .h file.

**Comment by Phil7789** [comment]
```
template<typename T>
void DynamicArray<T>::push_back(const T &value)
{
	if (m_length == m_capacity)
	{
		m_capacity *= 2;

		T *tmpArray = new T[m_capacity];

		for (int i = 0; i < m_length; ++i)
		{
			tmpArray[i] = m_data[i];
		}
		delete[] m_data;
		m_data = tmpArray;
	}
	m_data[m_length] = value;
	m_length++;
}
```

**Comment by n0lavar** [comment]
I pasted the code into a random header in my project and everything seems to work as expected. Are you sure you have this file in your solution? Because this won't work for a file outside of your project.
![image](https://user-images.githubusercontent.com/30406125/169366434-727120ed-bc05-4ac4-9c52-3d03f44363fc.png)

**Comment by n0lavar** [comment]
BTW 2 is really bad factor for capacity growing. see "Memory management": https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md

**Comment by n0lavar** [comment]
Can't reproduce
